name: Cargo Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the pact broker cli to release as'
        required: true
  repository_dispatch:
    types: [cargo-publish]

jobs:
  publish_crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          toolchain: stable
      - name: cargo login
        run: |-
          echo "${{ secrets.CRATES_IO_API_TOKEN }}" | cargo login
      - name: Publish to crates.io
        run: cargo publish
